apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook
  template:
    metadata:
      labels:
        app: webhook
    spec:
      containers:
        - name: webhook
          image: ghcr.io/sungeunsong/admission-webhook:latest
          ports:
            - containerPort: 443
          volumeMounts:
            - name: tls-certs
              mountPath: "/certs"
              readOnly: true
      volumes:
        - name: tls-certs
          secret:
            secretName: webhook-server-cert

